---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: installing java in rf and debian
    yum:
      name: java
      state: installed
    when: ansible_os_family == 'RedHat'

  - name: installing java in rf and debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == 'Debian'

  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz
      dest: /opt

  - name: extracting tomcat tar.gz
    unarchive:
      src: /opt/apache-tomcat-8.5.82.tar.gz
      dest: /opt
      remote_src: true
  
  - name: adding execute permissions
    file:
      path: /opt/apache-tomcat-8.5.82/bin/startup.sh
      mode: 0777
  
  - name: adding an empty file
    file:
      path: "/home/ansadmin/santosh"
      state: touch

  - name: starting tomcat
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.82/bin
